# see https://github.com/ankane/blazer for more info

data_sources:
  main:
    url: <%= ENV["BLAZER_DATABASE_URL"] || ENV["DATABASE_URL"] %>

    # statement timeout, in seconds
    # none by default
    timeout: 600

    # caching settings
    # can greatly improve speed
    # off by default
    cache:
      mode: slow # or all
      expires_in: 60 # min
      slow_threshold: 5 # sec, only used in slow mode

    # wrap queries in a transaction for safety
    # not necessary if you use a read-only user
    # true by default
    # use_transaction: false

    smart_variables:
      event_year:
        - 2011
        - 2012
        - 2013
        - 2014
        - 2015
        - 2016
        - 2017
        - 2018
        - 2019
        - 2020
        - 2021
        - 2022

      repo_name:
        - pingcap/tidb
        - tikv/tikv
        - clickhouse/clickhouse
        - apache/spark
        - elastic/elasticsearch
        - cockroachdb/cockroach
        - prometheus/prometheus
        - mongodb/mongo
        - trinodb/trino
        - redis/redis
        - apache/lucene-solr
        - apache/hbase
        - prestodb/presto
        - facebook/rocksdb
        - apache/druid
        - apache/hive
        - percona/percona-server
        - yugabyte/yugabyte-db
        - apache/lignite
        - apache/incubator-doris
        - citusdata/citus
        - timescale/timescaledb
        - apache/kylin
        - greenplum-db/gpdb
        - alibaba/oceanbase
        - influxdata/influxdb
        - vesoft-inc/nebula
        - scylladb/scylla
        - apache/hadoop
        - apache/couchdb

      language:
        - JavaScript
        - Python
        - Java
        - Ruby
        - HTML
        - PHP
        - C++
        - Go
        - C#
        - CSS
        - C
        - Shell
        - TypeScript
        - Scala
        - Rust

      oss_db_org:
        - pingcap
        - elastic
        - tikv

      oss_db_repo:
        - pingcap/tidb
        - tikv/tikv
        - clickhouse/clickhouse
        - apache/spark
        - elastic/elasticsearch
        - cockroachdb/cockroach
        - prometheus/prometheus
        - mongodb/mongo
        - trinodb/trino
        - redis/redis
        - apache/lucene-solr
        - apache/hbase
        - prestodb/presto
        - facebook/rocksdb
        - apache/druid
        - apache/hive
        - percona/percona-server
        - yugabyte/yugabyte-db
        - apache/lignite
        - apache/incubator-doris
        - citusdata/citus
        - timescale/timescaledb
        - apache/kylin
        - greenplum-db/gpdb
        - alibaba/oceanbase
        - influxdata/influxdb
        - vesoft-inc/nebula
        - scylladb/scylla
        - apache/hadoop
        - apache/couchdb

      top_n:
        - 10
        - 20
        - 30
        - 40
        - 50

      recent_years:
        - 10
        - 9
        - 8
        - 7
        - 6
        - 5
        - 4
        - 3
        - 2
        - 1

      event_type:
        - IssuesEvent
        - CreateEvent
        - PullRequestEvent
        - IssueCommentEvent
        - PushEvent
        - PullRequestReviewCommentEvent
        - DeleteEvent
        - CommitCommentEvent
        - ForkEvent
        - WatchEvent
        - GollumEvent
        - MemberEvent
        - PublicEvent
        - ReleaseEvent
        - PullRequestReviewEvent
        - GistEvent
        - FollowEvent
        - DownloadEvent
        - Event
        - ForkApplyEvent
        - TeamAddEvent
      # period: ["day", "week", "month"]
      # status: {0: "Active", 1: "Archived"}

    linked_columns:
      actor_login: "https://github.com/{value}"
      repo_name: "https://github.com/{value}"
      org_login: "https://github.com/{value}"

    smart_columns:
      # user_id: "SELECT id, name FROM users WHERE id IN {value}"

# create audits
audit: true

# change the time zone
# time_zone: "Pacific Time (US & Canada)"

# class name of the user model
# user_class: User

# method name for the current user
# user_method: current_user

# method name for the display name
# user_name: name

# custom before_action to use for auth
# before_action_method: require_admin

# email to send checks from
# from_email: blazer@example.org

# webhook for Slack
# slack_webhook_url: <%%= ENV["BLAZER_SLACK_WEBHOOK_URL"] %>

check_schedules:
  - "1 day"
  - "1 hour"
  - "5 minutes"

# enable anomaly detection
# note: with trend, time series are sent to https://trendapi.org
# anomaly_checks: trend / r

# enable forecasting
# note: with trend, time series are sent to https://trendapi.org
# forecasting: trend

# enable map
# mapbox_access_token: <%%= ENV["MAPBOX_ACCESS_TOKEN"] %>