default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  port: 4000
  variables:
    tidb_enable_noop_functions: ON
  username: root
  password:
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: blazer
test:
  <<: *default
  database: blazer_test
production:
  <<: *default
  database: blazer_pro